### ISSUE TITLE
decaffeinate HuViz

### ISSUE THREAD

**Issue by smurp** [smurp/huviz#102]
@Adsidera Perhaps we should co-work for a bit about this task.  Here are some considerations.

There are (of course) so many of these DS102 warnings and that serves as a reminder that we don't really want the Javascript code to be returning values for no reason. (I really hate this terrible mis-feature of coffeescript.  It is confusing, distracting, pointless, etc.) The easiest way to deal with this is probably to put explicit `return` (null) at the end of coffeescript methods which do not return values.

That means we'll be re-running the decaffeination until we like the level of correctness of this application of `return` (null).  This suggest that perhaps we should create a little script called `bin/decaf_all.sh` which runs the decaffeinate operation.  This way we can easily re-rerun it using this method.

Another thing that needs to happen is that we need to figure out the "build".  If this can be pure `npm` that would be great, I suppose, but using `gulp` is fine too.  I think we should retire our dependence on `grunt` because it is about configuration rather than code and is less flexible as a consequence.  Tied up with this is the `npm run dev` task so when code changes the build happens automatically.  Further, migration to the use of ES6 "modules" might best be handled in this operation.  Alternatively, this might be the easiest way to complete the changes to the build.

Sooooo....  If you feel like these are tasks you are OK with trying on your own, feel free... but at least a few of them are likely to most efficiently involve two sets of eyes.

**Comment by Adsidera** [comment]
yes, I think we'll have to pair on both issues, too.

**Comment by smurp** [comment]
Some guidance on how to accomplish build tasks using pure npm:
  * https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/
  * https://deliciousbrains.com/npm-build-script/
