### ISSUE TITLE
convert the other views to the use of npm-provided jquery and jquery-ui

### ISSUE THREAD

**Issue by smurp** [smurp/huviz#73]
Following the `jquery-ui` examples from ffe59ab and #72 for the __views/huviz.html.eco__ do the same thing to __views/orlonto.html.eco__, __views/tests.html.eco__, and __views/yegodd.html.eco__

The are viewable at 

* <http://localhost:9997/tests>
* <http://localhost:9997/orlonto.html>
* <http://localhost:9997/yegodd.html>

**Comment by wolfmaul** [comment]
New paths added
