### ISSUE TITLE
support multi-lingual labels

### ISSUE THREAD

**Issue by SusanBrown** [smurp/huviz#75]
We need the interface to support labeling for nodes. Right now the interface displays a mix of languages if there are multiple labels for a component of the graph.

See the ontology in progress here for example:
https://github.com/cwrc/ontology/blob/master/huvizTest.ttl

In the short term, simply defaulting to the "en" value for labels would be fine. 
In the long term, the user should be able to select the preferred language from those in the dataset.

**Comment by SusanBrown** [comment]
Possibly a related issue:

In the "orlonto" version of the interface, we are not having the problem with the random selection of labels irrespective of language. But we are seeing the nodes on the shelf as "undefined" and only seeing the labels when they are moved into the circle.

Is there anything missing from the ontology information that is at the root of this problem?

Here's the data file we are using:
https://github.com/cwrc/ontology/blob/master/huvizTest.ttl

**Comment by smurp** [comment]
Closed in favour of similar:
  https://github.com/cwrc/HuViz/issues/84
