### ISSUE TITLE
show skos:definitions as snippets

### ISSUE THREAD

**Issue by smurp** [smurp/huviz#78]
Motivated by the desire to show skos:definitions as snippets...

**Comment by SusanBrown** [comment]
When a node has an object of a predicate that is a string such as the object value of the skos:defn then instead of displaying those as things/nodes

[things are not displayed as nodes unless they have a typetriple associated with it to class it and a label e.g. rdf:label to be able to displayed]

**Comment by SusanBrown** [comment]
related to #76

**Comment by SusanBrown** [comment]
use chaining to make the association—have a “peek” verb on a node to get the object of the predicate “prov:derived from” or whatever was configured

hard coded for now

**Comment by smurp** [comment]
Closed in favour of #80
