### ISSUE TITLE
display nodes which have multiple classes as multi-colored-pies

### ISSUE THREAD

**Issue by smurp** [smurp/huviz#93]
To help debug various issues having to do with, eg nodes appearing black, nodes seeming to be in the wrong classes, etc it is helpful to be able to see all the classes that a node is actually a declared, explicit member of.  Also, it is very helpful to use this mode to validate and understand ontologies and their complexities.

* [x] show as a colored pie piece each of the classes that a node is a member of
* [x] put this capability behind a setting, default OFF
* [x] expose this setting (currently hidden and OFF)
* [x] debug something which needs debugging about this behaviour -- I don't remember what :-)

https://github.com/smurp/huviz/commit/0e93dc3b627fa6927ed1c9d9df905276fa672790
https://github.com/smurp/huviz/commit/f1ab3459392e613d99c4b247274d88e520129b1a

**Comment by wolfmaul** [comment]
The bug has been fixed.

**Comment by smurp** [comment]
I think there is a bug in this implementation which is causing some nodes to appear black.  I think this can be seen with `Dataset: REED Elizabethean sample` and `CWRC Ontology sans Genres`

**Comment by smurp** [comment]
replaced by https://github.com/cwrc/HuViz/issues/168
